
name: CI - Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: pytest -v

      - name: Verificar vulnerabilidades
        run: |
            bandit -r app.py -ll

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy no Render
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{ secrets.RENDER_SERVICE_ID_POC_DOCKER_COMPOSE }}
          wait-deploy: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
